name: Client Web App CI/CD Workflow

on:
    push:
        branches:
            - "NA" # prevent action

jobs:
    # pass data to reusable workflow
    configuration:
        name: "Configuration"
        uses: ./.github/workflows/config.yml

    buildClient:
        name: "Build Client App"

        needs: [configuration]
        runs-on: ubuntu-latest
        steps:
            # checkout the repo
            - name: "Checkout Repo"
              uses: actions/checkout@v2

            - name: "Login via Azure CLI"
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_SP_CREDENTIALS }}

            - name: Get APIM Gateway URL
              shell: pwsh
              run: |
                $gatewayUrl =  $(az apim show --name ${{ fromJson(needs.configuration.outputs.variables).apiManagementServiceName }} --resource-group ${{ fromJson(needs.configuration.outputs.variables).resourceGroup }} --output tsv --query gatewayUrl)
                  echo "gatewayUrl=$gatewayUrl" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

            - name: Variable replacement
              uses: microsoft/variable-substitution@v1
              with:
                files: "./web/client/src/util/Config.json"
              env:
                buildNumber: ver-${{ github.run_number }}
                rootApiUrl: ${{ env.gatewayUrl }}

            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                node-version: '16.x'
                    
              - name: Install Dependencies
                working-directory: ./web/client
                run: |
                  npm install --legacy-peer-deps
                  npm run build

              - name: Upload artifact for deployment job
                uses: actions/upload-artifact@v2
                with:
                  name: reactapp
                  path: ./web/client/build/

    deployClient:
        name: "Deploy Client App"
        needs: [configuration, buildClient]
        runs-on: ubuntu-latest
        steps:

            - name: Login via Azure CLI
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_SP_CREDENTIALS }}

            - name: Download artifact from build job
              uses: actions/download-artifact@v2
              with:
                name: reactapp

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${{ fromJson(needs.configuration.outputs.variables).webAppServiceName }}
                publish-profile: $
                package: .
